hs_user_index:
    path:     /user/index
    defaults: { _controller: HSUserBundle:User:index}

hs_user_create:
    path:     /user/create
    defaults: { _controller: HSUserBundle:User:create}

hs_user_store:
    path:     /user/store
    defaults: { _controller: HSUserBundle:User:store}
    methods:  POST

hs_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: HSUserBundle:User:edit}

hs_user_update:
    path:     /user/update/{id}
    defaults: { _controller: HSUserBundle:User:update}
    methods:  [POST, PUT]

hs_user_view:
    path:     /user/view/{id}
    defaults: { _controller: HSUserBundle:User:view}

hs_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: HSUserBundle:User:delete}
    methods:  [POST, DELETE]

hs_user_redirecd_create:
    path:     /user/store
    defaults:
        _controller: HSUserBundle:User:create
        path: /user/create
        permanent: true

hs_user_redirecd_edit:
    path:     /user/update/{id}
    defaults:
        _controller: HSUserBundle:User:edit
        path: /user/edit/{id}
        permanent: true