hs_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: HSUserBundle:Default:index }

hs_user_index:
    path:     /user/index
    defaults: { _controller: HSUserBundle:User:index}

hs_user_create:
    path:     /user/create
    defaults: { _controller: HSUserBundle:User:create}

hs_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: HSUserBundle:User:edit}

hs_user_view:
    path:     /user/view/{id}
    defaults: { _controller: HSUserBundle:User:view}

hs_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: HSUserBundle:User:delete}